spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.248.142:3306/rounx-db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password: abcd@1234
    druid:
      max-active: 20
      min-idle: 8
      initial-size: 10
      query-timeout: 6000
      transction-query-timeout: 6000
      remove-abandoned-timeout: 1800
      filter-class-names: stat
  redis:
    host: localhost
    port: 6379
    password:
    database: 8